<a href="https://colab.research.google.com/github/Ravi-Poddar26/missing-values/blob/master/H_M_V(8).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#iterative/mice imputer
import pandas as pd
import numpy as np

from sklearn.linear_model import LinearRegression

In [ ]:
df = pd.read_csv('https://raw.githubusercontent.com/campusx-official/100-days-of-machine-learning/main/day40-iterative-imputer/50_Startups.csv')

In [ ]:
df.sample(5)

,R&D Spend,Administration,Marketing Spend,State,Profit
3,144372.41,118671.85,383199.62,New York,182901.99
22,73994.56,122782.75,303319.26,Florida,110352.25
9,123334.88,108679.17,304981.62,California,149759.96
24,77044.01,99281.34,140574.81,New York,108552.04
41,27892.92,84710.77,164470.71,Florida,77798.83


In [ ]:
df = df.iloc[:,0:-1]


In [ ]:
df.head()

,R&D Spend,Administration,Marketing Spend,State,Profit
0,165349.20,136897.80,471784.10,New York,192261.83
1,162597.70,151377.59,443898.53,California,191792.06
2,153441.51,101145.55,407934.54,Florida,191050.39
3,144372.41,118671.85,383199.62,New York,182901.99
4,142107.34,91391.77,366168.42,Florida,166187.94


In [ ]:
df.iloc[1,0] = np.nan
df.iloc[3,1] = np.nan
df.iloc[-1,-1] = np.nan

In [ ]:

df.head()

,R&D Spend,Administration,Marketing Spend,State
0,165349.20,136897.80,471784.10,New York
1,NaN,151377.59,443898.53,California
2,153441.51,101145.55,407934.54,Florida
3,144372.41,NaN,383199.62,New York
4,142107.34,91391.77,366168.42,Florida


In [ ]:
# Step 1 - Impute all missing values with mean of respective col

df0 = pd.DataFrame()

df0['R&D Spend'] = df['R&D Spend'].fillna(df['R&D Spend'].mean())
df0['Administration'] = df['Administration'].fillna(df['Administration'].mean())
df0['Marketing Spend'] = df['Marketing Spend'].fillna(df['Marketing Spend'].mean())

In [ ]:

# 0th Iteration
df0

,R&D Spend,Administration,Marketing Spend
0,165349.200000,136897.800000,471784.10
1,71907.817959,151377.590000,443898.53
2,153441.510000,101145.550000,407934.54
3,144372.410000,121399.186327,383199.62
4,142107.340000,91391.770000,366168.42
5,131876.900000,99814.710000,362861.36
6,134615.460000,147198.870000,127716.82
7,130298.130000,145530.060000,323876.68
8,120542.520000,148718.950000,311613.29
9,123334.880000,108679.170000,304981.62


In [ ]:

# Remove the col1 imputed value
df1 = df0.copy()

df1.iloc[1,0] = np.nan

df1

,R&D Spend,Administration,Marketing Spend
0,165349.20,136897.800000,471784.10
1,NaN,151377.590000,443898.53
2,153441.51,101145.550000,407934.54
3,144372.41,121399.186327,383199.62
4,142107.34,91391.770000,366168.42
5,131876.90,99814.710000,362861.36
6,134615.46,147198.870000,127716.82
7,130298.13,145530.060000,323876.68
8,120542.52,148718.950000,311613.29
9,123334.88,108679.170000,304981.62


In [ ]:

# Use first 3 rows to build a model and use the last for prediction

X = df1.iloc[[0,2,3,4],1:3]
X

,Administration,Marketing Spend
0,136897.800000,471784.10
2,101145.550000,407934.54
3,121399.186327,383199.62
4,91391.770000,366168.42


In [ ]:

y = df1.iloc[[0,2,3,4],0]
y

,R&D Spend
0,165349.20
2,153441.51
3,144372.41
4,142107.34


In [ ]:

lr = LinearRegression()
lr.fit(X,y)
lr.predict(df1.iloc[1,1:].values.reshape(1,2))

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([156866.54270205])

In [ ]:

df1.iloc[1,0] = 23.14

In [ ]:

df1

,R&D Spend,Administration,Marketing Spend
0,165349.20,136897.800000,471784.10
1,23.14,151377.590000,443898.53
2,153441.51,101145.550000,407934.54
3,144372.41,121399.186327,383199.62
4,142107.34,91391.770000,366168.42
5,131876.90,99814.710000,362861.36
6,134615.46,147198.870000,127716.82
7,130298.13,145530.060000,323876.68
8,120542.52,148718.950000,311613.29
9,123334.88,108679.170000,304981.62


In [ ]:

# Remove the col2 imputed value

df1.iloc[3,1] = np.nan

df1

,R&D Spend,Administration,Marketing Spend
0,165349.20,136897.80,471784.10
1,23.14,151377.59,443898.53
2,153441.51,101145.55,407934.54
3,144372.41,NaN,383199.62
4,142107.34,91391.77,366168.42
5,131876.90,99814.71,362861.36
6,134615.46,147198.87,127716.82
7,130298.13,145530.06,323876.68
8,120542.52,148718.95,311613.29
9,123334.88,108679.17,304981.62


In [ ]:

# Use last 3 rows to build a model and use the first for prediction
X = df1.iloc[[0,1,2,4],[0,2]]
X

,R&D Spend,Marketing Spend
0,165349.20,471784.10
1,23.14,443898.53
2,153441.51,407934.54
4,142107.34,366168.42


In [ ]:

y = df1.iloc[[0,1,2,4],1]
y

,Administration
0,136897.80
1,151377.59
2,101145.55
4,91391.77


In [ ]:
lr = LinearRegression()
lr.fit(X,y)
lr.predict(df1.iloc[3,[0,2]].values.reshape(1,2))

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([96042.15312646])

In [ ]:

df1.iloc[3,1] = 11.06

In [ ]:

df1

,R&D Spend,Administration,Marketing Spend
0,165349.20,136897.80,471784.10
1,23.14,151377.59,443898.53
2,153441.51,101145.55,407934.54
3,144372.41,11.06,383199.62
4,142107.34,91391.77,366168.42
5,131876.90,99814.71,362861.36
6,134615.46,147198.87,127716.82
7,130298.13,145530.06,323876.68
8,120542.52,148718.95,311613.29
9,123334.88,108679.17,304981.62


In [ ]:
# Remove the col3 imputed value
df1.iloc[4,-1] = np.nan

df1

,R&D Spend,Administration,Marketing Spend
0,165349.20,136897.80,471784.10
1,23.14,151377.59,443898.53
2,153441.51,101145.55,407934.54
3,144372.41,11.06,383199.62
4,142107.34,91391.77,NaN
5,131876.90,99814.71,362861.36
6,134615.46,147198.87,127716.82
7,130298.13,145530.06,323876.68
8,120542.52,148718.95,311613.29
9,123334.88,108679.17,304981.62


In [ ]:

# Use last 3 rows to build a model and use the first for prediction
X = df1.iloc[0:4,0:2]
X

,R&D Spend,Administration
0,165349.20,136897.80
1,23.14,151377.59
2,153441.51,101145.55
3,144372.41,11.06


In [ ]:

y = df1.iloc[0:4,-1]
y

,Marketing Spend
0,471784.10
1,443898.53
2,407934.54
3,383199.62


In [ ]:
lr = LinearRegression()
lr.fit(X,y)
lr.predict(df1.iloc[4,0:2].values.reshape(1,2))

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([426486.19830015])

In [ ]:
df1.iloc[4,-1] = 31.56


In [ ]:

# After 1st Iteration
df1

,R&D Spend,Administration,Marketing Spend
0,165349.20,136897.80,471784.10
1,23.14,151377.59,443898.53
2,153441.51,101145.55,407934.54
3,144372.41,11.06,383199.62
4,142107.34,91391.77,31.56
5,131876.90,99814.71,362861.36
6,134615.46,147198.87,127716.82
7,130298.13,145530.06,323876.68
8,120542.52,148718.95,311613.29
9,123334.88,108679.17,304981.62


In [ ]:

# Subtract 0th iteration from 1st iteration

df1 - df0

,R&D Spend,Administration,Marketing Spend
0,0.000000,0.000000,0.00
1,-71884.677959,0.000000,0.00
2,0.000000,0.000000,0.00
3,0.000000,-121388.126327,0.00
4,0.000000,0.000000,-366136.86
5,0.000000,0.000000,0.00
6,0.000000,0.000000,0.00
7,0.000000,0.000000,0.00
8,0.000000,0.000000,0.00
9,0.000000,0.000000,0.00


In [ ]:

df2 = df1.copy()

df2.iloc[1,0] = np.nan

df2

,R&D Spend,Administration,Marketing Spend
0,165349.20,136897.80,471784.10
1,NaN,151377.59,443898.53
2,153441.51,101145.55,407934.54
3,144372.41,11.06,383199.62
4,142107.34,91391.77,31.56
5,131876.90,99814.71,362861.36
6,134615.46,147198.87,127716.82
7,130298.13,145530.06,323876.68
8,120542.52,148718.95,311613.29
9,123334.88,108679.17,304981.62


In [ ]:

X = df2.iloc[[0,2,3,4],1:3]
y = df2.iloc[[0,2,3,4],0]

lr = LinearRegression()
lr.fit(X,y)
lr.predict(df2.iloc[1,1:].values.reshape(1,2))

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([163966.86330711])

In [ ]:
df2.iloc[1,0] = 23.78


In [ ]:
df2.iloc[3,1] = np.nan
X = df2.iloc[[0,1,2,4],[0,2]]
y = df2.iloc[[0,1,2,4],1]

lr = LinearRegression()
lr.fit(X,y)
lr.predict(df2.iloc[3,[0,2]].values.reshape(1,2))

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([118978.40097602])

In [ ]:
df2.iloc[3,1] = 11.22


In [ ]:
df2.iloc[4,-1] = np.nan

X = df2.iloc[0:4,0:2]
y = df2.iloc[0:4,-1]

lr = LinearRegression()
lr.fit(X,y)
lr.predict(df2.iloc[4,0:2].values.reshape(1,2))

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([426486.1704513])

In [ ]:
df2.iloc[4,-1] = 31.56


In [ ]:
df2


,R&D Spend,Administration,Marketing Spend
0,165349.20,136897.80,471784.10
1,23.78,151377.59,443898.53
2,153441.51,101145.55,407934.54
3,144372.41,11.22,383199.62
4,142107.34,91391.77,31.56
5,131876.90,99814.71,362861.36
6,134615.46,147198.87,127716.82
7,130298.13,145530.06,323876.68
8,120542.52,148718.95,311613.29
9,123334.88,108679.17,304981.62


In [ ]:
df2 - df1


,R&D Spend,Administration,Marketing Spend
0,0.00,0.00,0.0
1,0.64,0.00,0.0
2,0.00,0.00,0.0
3,0.00,0.16,0.0
4,0.00,0.00,0.0
5,0.00,0.00,0.0
6,0.00,0.00,0.0
7,0.00,0.00,0.0
8,0.00,0.00,0.0
9,0.00,0.00,0.0


In [ ]:
df3 = df2.copy()

df3.iloc[1,0] = np.nan

df3


,R&D Spend,Administration,Marketing Spend
0,165349.20,136897.80,471784.10
1,NaN,151377.59,443898.53
2,153441.51,101145.55,407934.54
3,144372.41,11.22,383199.62
4,142107.34,91391.77,31.56
5,131876.90,99814.71,362861.36
6,134615.46,147198.87,127716.82
7,130298.13,145530.06,323876.68
8,120542.52,148718.95,311613.29
9,123334.88,108679.17,304981.62


In [ ]:
X= df3.iloc[[0,2,3,4],1:3]
y = df3.iloc[[0,2,3,4],0]

lr = LinearRegression()
lr.fit(X,y)
lr.predict(df3.iloc[1,1:].values.reshape(1,2))

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([163966.86870596])

In [ ]:
df3.iloc[1,0] = 24.57


In [ ]:

df3.iloc[3,1] = np.nan
X = df3.iloc[[0,1,2,4],[0,2]]
y = df3.iloc[[0,1,2,4],1]

lr = LinearRegression()
lr.fit(X,y)
lr.predict(df3.iloc[3,[0,2]].values.reshape(1,2))

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([118978.41439964])

In [ ]:
df3.iloc[3,1] = 11.37


In [ ]:

df3.iloc[4,-1] = np.nan

X = df3.iloc[0:4,0:2]
y = df3.iloc[0:4,-1]

lr = LinearRegression()
lr.fit(X,y)
lr.predict(df3.iloc[4,0:2].values.reshape(1,2))

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([426486.14275296])

In [ ]:
df3.iloc[4,-1] = 45.53


In [ ]:
df2.iloc[3,1] = 11.22


In [ ]:
df3


,R&D Spend,Administration,Marketing Spend
0,165349.20,136897.80,471784.10
1,24.57,151377.59,443898.53
2,153441.51,101145.55,407934.54
3,144372.41,11.37,383199.62
4,142107.34,91391.77,45.53
5,131876.90,99814.71,362861.36
6,134615.46,147198.87,127716.82
7,130298.13,145530.06,323876.68
8,120542.52,148718.95,311613.29
9,123334.88,108679.17,304981.62


In [ ]:
df3 - df2


,R&D Spend,Administration,Marketing Spend
0,0.00,0.00,0.00
1,0.79,0.00,0.00
2,0.00,0.00,0.00
3,0.00,0.15,0.00
4,0.00,0.00,13.97
5,0.00,0.00,0.00
6,0.00,0.00,0.00
7,0.00,0.00,0.00
8,0.00,0.00,0.00
9,0.00,0.00,0.00


In [ ]:
#this is also done by scikit learn